import PDFDocument from "pdfkit";

export const generateAnalysisPDF = (analysis, res) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=analysis-report-${analysis._id}.pdf`
  );

  doc.pipe(res);

  doc.fontSize(20).text("AI Resume Analyzer Report", { align: "center" });
  doc.moveDown();

  doc.fontSize(12).text(`Resume: ${analysis.resume?.originalName || "N/A"}`);
  doc.text(`ATS Score: ${analysis.atsScore}`);
  doc.text(`Match Percentage: ${analysis.matchPercentage}%`);
  doc.text(`Keyword Score: ${analysis.keywordScore}`);
  doc.text(`Structure Score: ${analysis.structureScore}`);
  doc.text(`Generated On: ${new Date(analysis.createdAt).toLocaleString()}`);
  doc.moveDown();

  doc.fontSize(16).text("Matched Keywords");
  doc.moveDown(0.5);
  doc.fontSize(11).text(
    analysis.matchedKeywords?.length
      ? analysis.matchedKeywords.join(", ")
      : "No matched keywords found"
  );
  doc.moveDown();

  doc.fontSize(16).text("Missing Keywords");
  doc.moveDown(0.5);
  doc.fontSize(11).text(
    analysis.missingKeywords?.length
      ? analysis.missingKeywords.join(", ")
      : "No missing keywords"
  );
  doc.moveDown();

  doc.fontSize(16).text("Suggested Skills");
  doc.moveDown(0.5);
  doc.fontSize(11).text(
    analysis.suggestedSkills?.length
      ? analysis.suggestedSkills.join(", ")
      : "No suggested skills"
  );
  doc.moveDown();

  doc.fontSize(16).text("Section-wise Breakdown");
  doc.moveDown(0.5);

  const sections = analysis.sectionAnalysis || {};

  doc.fontSize(11).text(
    `Skills: ${sections.skills?.score || 0} (${sections.skills?.status || "missing"})`
  );
  doc.text(
    `Education: ${sections.education?.score || 0} (${sections.education?.status || "missing"})`
  );
  doc.text(
    `Projects: ${sections.projects?.score || 0} (${sections.projects?.status || "missing"})`
  );
  doc.text(
    `Experience: ${sections.experience?.score || 0} (${sections.experience?.status || "missing"})`
  );
  doc.text(
    `Summary: ${sections.summary?.score || 0} (${sections.summary?.status || "missing"})`
  );
  doc.moveDown();

  doc.fontSize(16).text("Recommendations");
  doc.moveDown(0.5);

  if (analysis.recommendations?.length) {
    analysis.recommendations.forEach((item, index) => {
      doc.fontSize(11).text(`${index + 1}. ${item}`);
      doc.moveDown(0.3);
    });
  } else {
    doc.fontSize(11).text("No recommendations available");
  }

  doc.moveDown();
  doc.fontSize(10).fillColor("gray").text(
    "Generated by AI Resume Analyzer & ATS Optimizer",
    { align: "center" }
  );

  doc.end();
};